BeerFestTestEntityCodeFirst/Models/BeerEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BeerFestTestEntityCodeFirst.Models
{
    public class BeerEvent
    {
        public int BeerEventID { get; set; }
        public bool KyokaiBooth { get; set; }
        public int? Kegs { get; set; }
        public int? Bottles { get; set; }
        public decimal? KegVolume { get; set; }
        public decimal? BottleVolume { get; set; }
        public bool? SoldOut { get; set; } //totally sold out
        public bool? Out { get; set; } //sold out for the day
        public string AdditionalInfo { get; set; }
        public int? X { get; set; } //coordinates beer can be found on the map
        public int? Y { get; set; }

        // Foreign Key
        public int BeerID { get; set; }
        public int EventID { get; set; }

        // Navigation Properties
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Beer Beer { get; set; }

        public virtual Event Event { get; set; }
    }
}

BeerFestTestEntityCodeFirst/Models/BeerEventViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BeerFestTestEntityCodeFirst.Models
{
    public class BeerEventViewModel
    {
        public int BeerEventID { get; set; }
        public bool KyokaiBooth { get; set; }
        public int? Kegs { get; set; }
        public int? Bottles { get; set; }
        public decimal? KegVolume { get; set; }
        public decimal? BottleVolume { get; set; }
        public bool? SoldOut { get; set; } //totally sold out
        public bool? Out { get; set; } //sold out for the day
        public string AdditionalInfo { get; set; }
        public int? X { get; set; } //coordinates beer can be found on the map
        public int? Y { get; set; }

        // Foreign Key
        public int BeerID { get; set; }
        public int EventID { get; set; }

        // Navigation Properties
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Beer Beer { get; set; }

        public virtual Event Event { get; set; }
    }
}

BeerFestTestEntityCodeFirst/Controllers/BeerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeerFestTestEntityCodeFirst.Models;

namespace BeerFestTestEntityCodeFirst.Controllers
{
    public class BeerController : Controller
    {
        private BeerFesDB db = new BeerFesDB();

        // GET: /Beer/
        public ActionResult Index()
        {
            var beers = db.Beers.Include(b => b.BeerStyle);
            return View(beers.ToList());
        }

        // GET: /Beer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }

        // GET: /Beer/Create
        public ActionResult Create()
        {
            BeerCreateViewModel bcvm = new BeerCreateViewModel();
            bcvm.CompanyList = new SelectList(db.Companies.ToList(), "CompanyID", "Name");
            var styleid =
                db.BeerStyles
                    .Where(s => s.StyleName != null)
                    .AsEnumerable()
                    .Select(s => new
                    {
                        StyleID = s.BeerStyleID,
                        StyleName = string.Format("{0} - {1}", s.BeerStyleNumber.ToString(), s.StyleName.ToString())
                    })
                    .ToList();

            bcvm.BeerStyleList = new SelectList(styleid, "StyleID", "StyleName");
            return View(bcvm);
        }

        // POST: /Beer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="BeerID,Name,ABV,IBU,Edited,ImageID,BeerStyleID")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                db.Beers.Add(beer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BeerStyleID = new SelectList(db.BeerStyles, "BeerStyleID", "BeerStyleNumber", beer.BeerStyleID);
            return View(beer);
        }

        // GET: /Beer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            ViewBag.BeerStyleID = new SelectList(db.BeerStyles, "BeerStyleID", "BeerStyleNumber", beer.BeerStyleID);
            return View(beer);
        }

        // POST: /Beer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="BeerID,Name,ABV,IBU,Edited,ImageID,BeerStyleID")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BeerStyleID = new SelectList(db.BeerStyles, "BeerStyleID", "BeerStyleNumber", beer.BeerStyleID);
            return View(beer);
        }

        // GET: /Beer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Beer beer = db.Beers.Find(id);
            if (beer == null)
            {
                return HttpNotFound();
            }
            return View(beer);
        }

        // POST: /Beer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Beer beer = db.Beers.Find(id);
            db.Beers.Remove(beer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeerFestTestEntityCodeFirst/Controllers/BeerEventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeerFestTestEntityCodeFirst.Models;

namespace BeerFestTestEntityCodeFirst.Controllers
{
    public class BeerEventController : Controller
    {
        private BeerFesDB db = new BeerFesDB();

        // GET: /BeerEvent/
        public ActionResult Index()
        {
            var beerevents = db.BeerEvents.Include(b => b.Beer).Include(b => b.Event);
            return View(beerevents.ToList());
        }

        // GET: /BeerEvent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            //BeerEvent beerevent = db.BeerEvents.Find(id);
            var beerevents = db.BeerEvents
                .Include(b => b.Beer)
                .Include(b => b.Event)
                .Where(x => x.EventID == id);
            if (beerevents == null)
            {
                return HttpNotFound();
            }
            return View(beerevents);

        }

        // GET: /BeerEvent/Create
        public ActionResult Create()
        {
            ViewBag.BeerID = new SelectList(db.Beers, "BeerID", "Name");
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name");
            return View();
        }

        // POST: /BeerEvent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="BeerEventID,KyokaiBooth,Kegs,Bottles,KegVolume,BottleVolume,SoldOut,Out,AdditionalInfo,X,Y,BeerID,EventID")] BeerEvent beerevent)
        {
            if (ModelState.IsValid)
            {
                db.BeerEvents.Add(beerevent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BeerID = new SelectList(db.Beers, "BeerID", "Name", beerevent.BeerID);
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", beerevent.EventID);
            return View(beerevent);
        }

        // GET: /BeerEvent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BeerEvent beerevent = db.BeerEvents.Find(id);
            if (beerevent == null)
            {
                return HttpNotFound();
            }
            ViewBag.BeerID = new SelectList(db.Beers, "BeerID", "Name", beerevent.BeerID);
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", beerevent.EventID);
            return View(beerevent);
        }

        // POST: /BeerEvent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="BeerEventID,KyokaiBooth,Kegs,Bottles,KegVolume,BottleVolume,SoldOut,Out,AdditionalInfo,X,Y,BeerID,EventID")] BeerEvent beerevent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(beerevent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BeerID = new SelectList(db.Beers, "BeerID", "Name", beerevent.BeerID);
            ViewBag.EventID = new SelectList(db.Events, "EventID", "Name", beerevent.EventID);
            return View(beerevent);
        }

        // GET: /BeerEvent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BeerEvent beerevent = db.BeerEvents.Find(id);
            if (beerevent == null)
            {
                return HttpNotFound();
            }
            return View(beerevent);
        }

        // POST: /BeerEvent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BeerEvent beerevent = db.BeerEvents.Find(id);
            db.BeerEvents.Remove(beerevent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeerFestTestEntityCodeFirst/Views/BeerEvent/Create.cshtml
@model BeerFestTestEntityCodeFirst.Models.BeerEvent

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BeerEvent</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.KyokaiBooth, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KyokaiBooth)
                @Html.ValidationMessageFor(model => model.KyokaiBooth)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kegs, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kegs)
                @Html.ValidationMessageFor(model => model.Kegs)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bottles, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bottles)
                @Html.ValidationMessageFor(model => model.Bottles)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KegVolume, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KegVolume)
                @Html.ValidationMessageFor(model => model.KegVolume)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottleVolume, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BottleVolume)
                @Html.ValidationMessageFor(model => model.BottleVolume)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldOut, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldOut)
                @Html.ValidationMessageFor(model => model.SoldOut)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Out, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Out)
                @Html.ValidationMessageFor(model => model.Out)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalInfo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdditionalInfo)
                @Html.ValidationMessageFor(model => model.AdditionalInfo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.X, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.X)
                @Html.ValidationMessageFor(model => model.X)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Y, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Y)
                @Html.ValidationMessageFor(model => model.Y)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeerID, "BeerID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BeerID", String.Empty)
                @Html.ValidationMessageFor(model => model.BeerID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventID, "EventID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventID", String.Empty)
                @Html.ValidationMessageFor(model => model.EventID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeerFestTestEntityCodeFirst/Views/BeerEvent/Delete.cshtml
@model BeerFestTestEntityCodeFirst.Models.BeerEvent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BeerEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Beer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beer.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KyokaiBooth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KyokaiBooth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kegs)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kegs)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bottles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bottles)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KegVolume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KegVolume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BottleVolume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BottleVolume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoldOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoldOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Out)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Out)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdditionalInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdditionalInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.X)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.X)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Y)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Y)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BeerFestTestEntityCodeFirst/Views/BeerEvent/Details.cshtml
@model IEnumerable<BeerFestTestEntityCodeFirst.Models.BeerEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Company
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kegs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bottles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoldOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Out)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdditionalInfo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <table>
                    @foreach (var company in item.Companies)
                    {
                        <tr>
                            <td>@company.TypeID.ToString()</td>
                            <td><a href="@Url.Action("Details", "Company", new { id=company.CompanyID })">@Html.DisplayFor(modelItem => company.Name)</a></td>
                        </tr>
                    }
                </table>
            </td>

            <td>
                <a href="@Url.Action("Details", "Beer", new { id=item.Beer.BeerID })">@Html.DisplayFor(modelItem => item.Beer.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kegs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bottles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoldOut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Out)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalInfo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.BeerEventID }) |
                @Html.ActionLink("Details", "Details", new { id = item.BeerEventID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.BeerEventID })
            </td>
        </tr>
    }

</table>

BeerFestTestEntityCodeFirst/Views/BeerEvent/Edit.cshtml
@model BeerFestTestEntityCodeFirst.Models.BeerEvent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BeerEvent</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.BeerEventID)

        <div class="form-group">
            @Html.LabelFor(model => model.KyokaiBooth, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KyokaiBooth)
                @Html.ValidationMessageFor(model => model.KyokaiBooth)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kegs, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kegs)
                @Html.ValidationMessageFor(model => model.Kegs)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bottles, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bottles)
                @Html.ValidationMessageFor(model => model.Bottles)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KegVolume, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KegVolume)
                @Html.ValidationMessageFor(model => model.KegVolume)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BottleVolume, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BottleVolume)
                @Html.ValidationMessageFor(model => model.BottleVolume)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoldOut, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoldOut)
                @Html.ValidationMessageFor(model => model.SoldOut)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Out, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Out)
                @Html.ValidationMessageFor(model => model.Out)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalInfo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdditionalInfo)
                @Html.ValidationMessageFor(model => model.AdditionalInfo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.X, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.X)
                @Html.ValidationMessageFor(model => model.X)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Y, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Y)
                @Html.ValidationMessageFor(model => model.Y)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BeerID, "BeerID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BeerID", String.Empty)
                @Html.ValidationMessageFor(model => model.BeerID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventID, "EventID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventID", String.Empty)
                @Html.ValidationMessageFor(model => model.EventID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BeerFestTestEntityCodeFirst/Views/BeerEvent/Index.cshtml
@model IEnumerable<BeerFestTestEntityCodeFirst.Models.BeerEvent>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Beer.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Event.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KyokaiBooth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kegs)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bottles)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KegVolume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BottleVolume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoldOut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Out)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdditionalInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.X)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Y)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Beer.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Event.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KyokaiBooth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kegs)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bottles)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KegVolume)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BottleVolume)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoldOut)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Out)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdditionalInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.X)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Y)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BeerEventID }) |
            @Html.ActionLink("Details", "Details", new { id=item.BeerEventID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BeerEventID })
        </td>
    </tr>
}

</table>